module.exports = {
  purge: ["./components/**/*.js", "./pages/**/*.js"],
  theme: {
    extend: {
      minWidth: {
        "1/4": "25%",
        "1/2": "50%",
        "3/4": "75%",
        "10": "2.5rem",
        "12": "3rem",
        "16": "4rem",
        "20": "5rem",
        "24": "6rem",
        "32": "8rem",
        "40": "10rem",
        "48": "12rem",
        "56": "14rem",
        "64": "15rem",
      },
      minHeight: {
        "1/4": "25%",
        "1/2": "50%",
        "3/4": "75%",
        "10": "2.5rem",
        "12": "3rem",
        "16": "4rem",
        "20": "5rem",
        "24": "6rem",
        "32": "8rem",
        "40": "10rem",
        "48": "12rem",
        "56": "14rem",
        "64": "15rem",
      },
      colors: {
        blue: {
          default: "var(--main-500)",
          "100": "var(--main-100)",
          "200": "var(--main-200)",
          "300": "var(--main-300)",
          "400": "var(--main-400)",
          "500": "var(--main-500)",
          "600": "var(--main-600)",
          "700": "var(--main-700)",
          "800": "var(--main-800)",
          "900": "var(--main-900)",
        },
        primary: "var(--primary)",
        ["primary-dark"]: "var(--primary-dark)",
        ["primary-darker"]: "var(--primary-darker)",
        ["primary-light"]: "var(--primary-light)",
        ["primary-lighter"]: "var(--primary-lighter)",

        secondary: "var(--secondary)",
        ["secondary-dark"]: "var(--secondary-dark)",
        ["secondary-darker"]: "var(--secondary-darker)",
      },
    },
    fontFamily: {
      body: ["Circular", "sans-serif"],
    },
  },
  variants: {
    opacity: ["responsive", "hover", "focus", "disabled"],
    cursor: ["responsive", "disabled"],
  },
  plugins: [],
};
