export const colors = [
  {
    100: "#cce1ff",
    200: "#99c3ff",
    300: "#66a6ff",
    400: "#3388ff",
    500: "#006aff",
    600: "#0055cc",
    700: "#004099",
    800: "#002a66",
    900: "#001533",
  },
  {
    100: "#FFF5F5",
    200: "#FED7D7",
    300: "#FEB2B2",
    400: "#FC8181",
    500: "#F56565",
    600: "#E53E3E",
    700: "#C53030",
    800: "#9B2C2C",
    900: "#742A2A",
  },
  {
    100: "#FFFAF0",
    200: "#FEEBC8",
    300: "#FBD38D",
    400: "#F6AD55",
    500: "#ED8936",
    600: "#DD6B20",
    700: "#C05621",
    800: "#9C4221",
    900: "#7B341E",
  },
  {
    100: "#FFFFF0",
    200: "#FEFCBF",
    300: "#FAF089",
    400: "#F6E05E",
    500: "#ECC94B",
    600: "#D69E2E",
    700: "#B7791F",
    800: "#975A16",
    900: "#744210",
  },
  {
    100: "#F0FFF4",
    200: "#C6F6D5",
    300: "#9AE6B4",
    400: "#68D391",
    500: "#48BB78",
    600: "#38A169",
    700: "#2F855A",
    800: "#276749",
    900: "#22543D",
  },
  {
    100: "#E6FFFA",
    200: "#B2F5EA",
    300: "#81E6D9",
    400: "#4FD1C5",
    500: "#38B2AC",
    600: "#319795",
    700: "#2C7A7B",
    800: "#285E61",
    900: "#234E52",
  },
  {
    100: "#FAF5FF",
    200: "#E9D8FD",
    300: "#D6BCFA",
    400: "#B794F4",
    500: "#9F7AEA",
    600: "#805AD5",
    700: "#6B46C1",
    800: "#553C9A",
    900: "#44337A",
  },
  {
    100: "#FFF5F7",
    200: "#FED7E2",
    300: "#FBB6CE",
    400: "#F687B3",
    500: "#ED64A6",
    600: "#D53F8C",
    700: "#B83280",
    800: "#97266D",
    900: "#702459",
  },
];
export const getColorObject = () => {
  return getRandomArrayElement(colors);
};

export const getRandomArrayElement = (arr) =>
  arr[Math.floor(Math.random() * arr.length)];

export const listOfProject = [
  {
    title: "Replayed Dashboard",
    description: "Video Editing Managment Dashboard",
    imageURL: "project-13.gif",
    stack: ["REACT", "JAVASCRIPT", "GROMMET", "STRIPE", "DROPBOX"],
    demoLink: "https://app.replayed.co/",
  },
  {
    title: "Hacker News",
    description: "Trending News React App",
    imageURL: "project-12.png",
    stack: ["REACT", "JAVASCRIPT"],
    demoLink: "https://imsolitude.github.io/HackerNews/",
    githubLink: "https://github.com/ImSolitude/HackerNews",
  },
  {
    title: "Skippit",
    description: "Skippit's React Landing Page",
    imageURL: "project-11.png",
    stack: ["REACT", "JAVASCRIPT", "ANT.DESIGN", "CLOUD FIREBASE"],
    demoLink: "https://skippitapp.com/",
  },
  {
    title: "Replayed",
    description: "Replayed Co's Landing Page",
    imageURL: "project-10.png",
    stack: ["JAVASCRIPT", "BOOTSTRAP", "HTML", "CSS"],
    demoLink: "https://replayed.co/",
  },
  {
    title: "ReacTrivia",
    description: "React Quiz App",
    imageURL: "project-9.png",
    stack: ["REACT", "JAVASCRIPT"],
    demoLink: "https://imsolitude.github.io/ReacTrivia/",
    githubLink: "https://github.com/ImSolitude/ReacTrivia",
  },
  {
    title: "ReactCalculator",
    description: "Simple React Calculator",
    imageURL: "project-8.png",
    stack: ["REACT", "JAVASCRIPT", "HTML", "CSS"],
    demoLink: "https://imsolitude.github.io/ReactCalculator/",
    githubLink: "https://github.com/ImSolitude/ReactCalculator",
  },
  {
    title: "QuoteNext",
    description: "React Random Quotes Generator",
    imageURL: "project-7.png",
    stack: ["REACT", "JAVASCRIPT", "HTML", "CSS"],
    demoLink: "https://imsolitude.github.io/QuoteNext/",
    githubLink: "https://github.com/ImSolitude/QuoteNext",
  },
  {
    title: "MarketWhale",
    description: "React Inventory Web App",
    imageURL: "project-6.png",
    stack: ["REACT", "JAVASCRIPT", "HTML", "CSS"],
    demoLink: "https://market-whale-mj.netlify.com/",
    githubLink: "https://github.com/ImSolitude/market-whale",
  },
  {
    title: "GitDiamond",
    description: "App Landing Page",
    imageURL: "project-5.png",
    stack: ["JAVASCRIPT", "BOOTSTRAP", "HTML", "CSS"],
    demoLink: "https://imsolitude.github.io/GitDiamond/",
    githubLink: "https://github.com/ImSolitude/GitDiamond",
  },
  {
    title: "PCTrance",
    description: "Gaming Website Landing Page",
    imageURL: "project-4.png",
    stack: ["JAVASCRIPT", "BOOTSTRAP", "HTML", "CSS"],
    demoLink: "https://imsolitude.github.io/PCTrance/",
    githubLink: "https://github.com/ImSolitude/PCTrance",
  },
  {
    title: "QuickFood",
    description: "Web App UI Concept",
    imageURL: "project-3.png",
    stack: ["JQUERY", "HTML", "CSS"],
    demoLink: "https://imsolitude.github.io/QuickFood/",
    githubLink: "https://github.com/ImSolitude/QuickFood",
  },
  {
    title: "Hover Styles",
    description: "On Hover Ready-to-use UI Snippets",
    imageURL: "project-2.png",
    stack: ["HTML", "CSS"],
    demoLink: "https://imsolitude.github.io/hover-styles/",
    githubLink: "https://github.com/ImSolitude/hover-styles",
  },
  {
    title: "MeteorX",
    description: "Jekyll-based Landing Page",
    imageURL: "project-1.png",
    stack: ["JEKYLL", "HTML", "CSS"],
    demoLink: "https://imsolitude.github.io/MeteorX/",
    githubLink: "https://github.com/ImSolitude/MeteorX",
  },
];
